### ISSUE TITLE
Figure out a reasonable reusable module/packaging approach

### ISSUE THREAD

**Issue by douglasnaphas** [douglasnaphas/setty#1]
[Design doc](https://docs.google.com/spreadsheets/d/1bgdXuiz_jKQAf8a3EiB1O0SdnOOdCvfgxjDKRj6dDfk/edit?usp=sharing).

**Comment by douglasnaphas** [comment]
# TODO
- [ ] Factor the string-determination logic in `hello` to an import.
- [ ] Import the `hello` library from Cabana.
- [ ] Apply the above to my OIDC repo.

**Comment by douglasnaphas** [comment]
I can export and import as of the latest commit. A "reasonable approach" would have to include a build/package step. Currently I'm using `TS_NODE_SKIP_IGNORE=true` so that I can import uncompiled TS files from GitHub.
